### ISSUE TITLE
Update soul-dashbord to shenyu.

### ISSUE THREAD

**Issue by fengzhenbing** [dromara/shenyu-dashboard#112]
- [x] replace  the key `SOUL`   in locale files en-US.json and zh-CN.json with  `SHENYU`.
- [x]  replace any pages with  `shenYu`  where contains `soul`.
- [x] change the service api to adapt the ShenYu backend.

**Comment by hubao-1125** [comment]
I think you must get task, soul rename to shenyu front task is mine, Maybe we can complete front task together, what do you think about my think?

**Comment by hubao-1125** [comment]
I get this task

**Comment by fengzhenbing** [comment]
This is finished by https://github.com/dromara/shenyu-dashboard/pull/113
