### ISSUE TITLE
in divide selector handler  , protocol  not  Required

### ISSUE THREAD

**Issue by yu199195** [dromara/shenyu-dashboard#114]
![微信图片_20210520111541](https://user-images.githubusercontent.com/9673503/118913803-c0572b00-b95c-11eb-9fa6-97d9a70168e6.png)

**Comment by qurenneng** [comment]
I've come to

**Comment by fengzhenbing** [comment]
> I've come to

Maybe you will update the configuration in pluginhandle page and update the schema.sql dml in Shenyu.
