### ISSUE TITLE
MatchType and Conditions dropdown box data  Used By plugin-data table data

### ISSUE THREAD

**Issue by yu199195** [dromara/shenyu-dashboard#115]
![微信图片_20210521155932](https://user-images.githubusercontent.com/9673503/119103320-9af61a00-ba4d-11eb-8fab-d18320596b77.png)

**Comment by yu199195** [comment]
![Uploading 微信图片_20210521155932.png…]()

**Comment by fengzhenbing** [comment]
the selector items of  MatchType, Conditions and Operators  should be fetched from  shenyu_dic in dictionary page.
