### ISSUE TITLE
Optimize editor modal to  allow update resourcePath  in Authentication page.

### ISSUE THREAD

**Issue by fengzhenbing** [dromara/shenyu-dashboard#117]
- [ ] Optimize editor modal to  allow update resourcePath  in Authentication page.
Here is the add page.
![image](https://user-images.githubusercontent.com/4169359/119842871-a2c82980-bf39-11eb-81e8-927b27bba86a.png)

Here is the editor page.
![image](https://user-images.githubusercontent.com/4169359/119843166-df942080-bf39-11eb-85dd-2f881a397a29.png)

- [ ] Optimize some display style.

**Comment by fightingting** [comment]
please assign this to me
